### ISSUE TITLE
Next up dialogue box is full screen 

### ISSUE THREAD

**Issue by Bhav1111** [Ezra-Hubbard/Ezra-Hubbard.github.io#23] opened 2022-07-07 23:55 UTC
Next up dialogue box is not in corner but stretched full screen. Buttons show up on bottom right.

**Comment by Ezra-Hubbard** [comment] 2022-07-08 00:49
Duplicate of https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/issues/22

Fixed in https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/commit/d84ea1c039b46ec901a0f5694909413e4a4e2ca3~

Use Issue 22 if it continues to be a problem. :D

Sorry about that

**Closed by Ezra-Hubbard** 2022-07-08 00:49 UTC
