### ISSUE TITLE
[Bug] Constant error messages being displayed after file playback

### ISSUE THREAD

**Issue by Madddcow** [Ezra-Hubbard/Ezra-Hubbard.github.io#24] opened 2022-07-15 14:55 UTC
I'm seeing a lot of errors in the Kodi log from my Nvidia Shield 2019 install of Kodi 19.4 that appear to be from Ezra. The most frequent error is displayed onscreen once streamed file playback has completed IN ADDITION TO the regular Trakt sync: 

EZRA 'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')

**Log**
Attached.

**Environment**
 - Operating System: Nvidia Shield 2019
 - Kodi Version: 19.4
 - Seren Version: 2.2.1

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.
[kodi.log](https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/files/9121849/kodi.log)

**Comment by Ezra-Hubbard** [comment] 2022-07-15 18:06
That log is bug spaghetti, you have a lot going on there.

There are trakt errors 

```
2022-07-14 02:27:20.060 T:12003   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ConnectionError'>
                                                   Error Contents: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/last_activities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2586e84de0>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
```

There are Seren errors

```
ERROR <general>: SEREN (-1): Failed to check account status: HTTPSConnectionPool(host='api.real-debrid.com', port=443): Max retries exceeded with url: /rest/1.0/user (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x25871e01a0>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
```

Other addon errors

```
ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2022-07-14 02:42:59.388 T:13006   ERROR <general>: CCurlFile::Open failed with code 0 for https://raw.githubusercontent.com/teamuniversal/scrapers/master/_modules4all/zips/addons.xml.md5:
                                                   
2022-07-14 02:42:59.388 T:13006   ERROR <general>: CFileCache::Open - <https://raw.githubusercontent.com/teamuniversal/scrapers/master/_modules4all/zips/addons.xml.md5> failed to open
2022-07-14 02:42:59.388 T:13006   ERROR <general>: CRepository: failed read 'https://raw.githubusercontent.com/teamuniversal/scrapers/master/_modules4all/zips/addons.xml.md5'
```

Errors trying to access Kingpin repo

```
2022-07-14 02:42:59.471 T:13006   ERROR <general>: CCurlFile::Open failed with code 0 for https://raw.githubusercontent.com/Wilson-Fisk/Wilson-Fisk.github.io/master/repo/zips/addons.xml.md5:
                                                   
2022-07-14 02:42:59.472 T:13006   ERROR <general>: CFileCache::Open - <https://raw.githubusercontent.com/Wilson-Fisk/Wilson-Fisk.github.io/master/repo/zips/addons.xml.md5> failed to open
2022-07-14 02:42:59.472 T:13006   ERROR <general>: CRepository: failed read 'https://raw.githubusercontent.com/Wilson-Fisk/Wilson-Fisk.github.io/master/repo/zips/addons.xml.md5'
2022-07-14 02:42:59.489 T:13006   ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2022-07-14 02:42:59.489 T:13006   ERROR <general>: CCurlFile::Open failed with code 0 for https://raw.githubusercontent.com/nixgates/nixgates/master/repo/zips/addons.xml.md5:
```

More seren errors

```
 ERROR <general>: SEREN (-1): Connection Error to Trakt: (<resources.lib.indexers.trakt.TraktAPI object at 0x258799eca0>,) - {'url': 'sync/last_activities'}
2022-07-15 11:38:48.738 T:32496   ERROR <general>: SEREN (-1): HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/last_activities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2587623b20>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
```

More trakt errors

```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ConnectionError'>
                                                   Error Contents: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/last_activities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x25874e1fa0>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
```

I will be honest, in the middle of all that I could not even find the Ezra errors, but if they are appearing after you have finished watching something they are, bearing in mind all of the above. Likely to be trakt errors.

Whatever you have going on you have major connections errors everywhere, and trakt rejecting you for flooding by the looks. 

Do notice that you have trakt from Ezra being rejected as well

```
###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Failed. Error from Trakt - Next Update in 10
```
Either, trakt has issues, or you have a ton of addons all hitting trakt for updates and you are flooding and getting locked out :S

**Comment by Ezra-Hubbard** [comment] 2022-07-15 18:08
But, I gotta be honest, you've got literally hundreds of errors in there, all connection related, from multiple different add-ons and repos (trakt, ezra, seren, kodi itself, kingpin, etc etc)

My hunch is you are flooding trakt and getting rejected, but, that many errors theres no way to figure out if Ezra itself is at fault, because theres so much going on. :S

**Comment by kodifitzwell** [comment] 2022-07-15 19:35
if I could add my guess-timations, yours isn't really an addon/trakt issue.  this seems to be prevalent on android with and/or and kodi.  looking at the log, its not just ezra/seren/**requests** failing with trakt, there hundreds of **curl** fails where it looks like kodi is checking repositories for updates.  almost like kodi can't reach the outside internet.

I haven't looked at all the other addons code, but I presume what is unique to Fen forks is that the error is logged to kodi.log **AND** a visual notification is given.  so if we wanted to handle it more quietly, from *trakt_api.py* swap a couple lines:

    def call_trakt(path, params={}, data=None, is_delete=False, with_auth=True, method=None, pagination=False, page=1, suppress_error_notification=False):
        def error_notification(line1, error):
            if suppress_error_notification: return
            logger(line1, error)
            return kodi_utils.notification('%s: %s' % (line1, error[0:50]), 3000, trakt_icon)

to:

    def call_trakt(path, params={}, data=None, is_delete=False, with_auth=True, method=None, pagination=False, page=1, suppress_error_notification=False):
        def error_notification(line1, error):
            logger(line1, error)                      #swapped
            if suppress_error_notification: return    #swapped
            return kodi_utils.notification('%s: %s' % (line1, error[0:50]), 3000, trakt_icon)


or handle the exception differently further down:

    except ConnectionResetError:
        # retry / return none / or do something else


I think umbrella may have done something related to allowing a longer timeout for the call, but anything past the 20 already set seems ridiculous.

lastly, I got lost on stackoverflow one night over this and there might be a couple different options to try regarding requests, but I/he/we? would probably rather have you download a zip and try independently rather than push update after update.  but again, because it seems like even kodi itself is failing to reach the outside, it could all be for none.

**Comment by Madddcow** [comment] 2022-07-15 22:48
Thanks for replying, guys. I know there's a lot going on. I wonder if it's an Android thing because I checked the log for the FireStick setup in our bedroom and it seems to have a lot of similar things happening....whereas none of these errors are occurring on my MacBook Pro and it's the same setup as the two Android devices.  Attached is the log from my FireStick
[Bedroom kodi.log](https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/files/9124555/Bedroom.kodi.log)
.

**Comment by Madddcow** [comment] 2022-07-15 22:52
To be honest, I don't really care so much about the errors EXCEPT for the Ezra error that's always displayed at the top of the screen.  It's quite annoying, especially when we're watching something.  Perhaps there could be an option not to display the Ezra errors?

**Comment by kodifitzwell** [comment] 2022-07-16 00:10
[https://paste.kodi.tv/figexiliwu.kodi](https://paste.kodi.tv/figexiliwu.kodi)

from the bedroom log, when you filter out most of the other stuff a clear pattern is shown.  TraktMonitor will succeed and 30 mins later it will fail because of ConnectionResetError.  +30 min it will succeed and then fail again +30 mins.  you could try setting trakt cache to 60+ mins (or <30?) in settings and see if that helps.

there are also a dozen+ seren ConnectionResetError in there, but no real pattern so idk.

lastly, you have an orphaned addon trying real hard to connect to ```raw.githubusercontent.com/123Venom/repository.venom/main/repo/zips/addons.xml.md5```.  you should find out which one and remove the addon.

**Comment by Madddcow** [comment] 2022-07-16 01:56
@kodifitzwell, thanks so much for your help.  I've tried changing Ezra's Trakt cache to intervals shorter than 30 mins and the result is the same.  I've just changed this to 60 mins on both the Nvidia Shield and bedroom FireStick to see what happens.

I hadn't realised I still had the Venom repo installed and have now removed it...thanks for the heads-up.

Regardless of the Seren errors, it definitely seems that there's an issue related to Ezra and Trakt...I don't experience any issues with The Crow, The Oath, Kingpin, Asgard etc.  All of those plugins sync just fine and there are no behind-the-scenes errors in the log. What's really annoying is the Ezra error that pops up at the top of the menu bar.  At least Seren has the decency not to disturb its users :)

I've raised the Seren errors with the dev and will see what he/she says.

**Comment by umbrellaplug** [comment] 2022-07-16 02:28
I have been watching from the sidelines, but I'd like to jump in and help here. 

A shield is a powerful device to be crashing. You guys are going to hate this response, but I think trakt may be part of it, but I'm really suspecting the scrapers + trakt = flooding connections and crashing this. 
They stated it's happening toward the end of videos on its own, this could be related to the "upnext" changes you've been doing also. So could be skin, could be scrapers, could be plugin. We REALLY need good logs on this one. You've got everyone's attention right now, I read through the above but I didn't see if anyone had asked him to put the kodi into debug mode for the log? I know it's going to be terrible (you guys need a way to isolate your plugin log). Also can they turn the logs on for the scrapers also?

@kodifitzwell have you or ezra written anything into your code to handle the bad 401 responses from trakt? You were avoiding it for the most part before because the code was written in a way where it would only happen if it wasn't in an active video, but the issue is still there. Could this be part of the problem if it hasn't been fixed?

I'm not pointing blame or anything at all here, I had a hell of a time with this same issue last week. Mine ended up being scraper related. So please don't take all my questions and speculation as being any type of way.

So basic questions: 

are you using autoplay with next up?
can you turn the logs on for the scrapers?
can you put it in debug mode and try to make the crash happen?
are you using any skins on these devices?

**Comment by Madddcow** [comment] 2022-07-16 02:46
@umbrellaplug, thanks for the info...great stuff.  To answer your questions:
Are you using autoplay with next up? _Only autoplay....no next up._
Can you turn the logs on for the scrapers? _Will do._
Can you put it in debug mode and try to make the crash happen? _Will do._
Are you using any skins on these devices? _Yep, I'm using Aeon Nox on all devices._

As mentioned above, I don't appear to experiencing any of these issues with my MacBook Pro.  However, I admit that I'm not using this for Kodi nearly as much as the Shield and FireStick, so perhaps I just haven't run it long enough for errors to occur. But with this being said, occurs start occurring with Ezra and Seren in a very short period of time after starting Kodi.  As an example, attached is a regular log after Kodi has been running on the Shield for just over 1 hour.
[kodi.log](https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/files/9125028/kodi.log)

**Comment by umbrellaplug** [comment] 2022-07-16 02:54
3 things.
1. You've got an error in the skin helper service that's running. Might want to check for updates there.
2. Looks like you still have an orphaned repo. (https://github.com/host505/repository.host505/raw/master/addons.xml.md5)
3. Seren is the main culprit in this log, I don't see a single ezra issue in that log at all and I'm not partial here. Neither of these are my plugin. :)

Try running ezra on one without seren installed and see if the issue goes away.

**Comment by kodifitzwell** [comment] 2022-07-16 03:14
I have not done anything about 401 other than the way it is already handled.  I may be wrong as I'm really new to python and kodi, but I think with Fen forks, the exception gets thrown before it even tests for 401.

but I would be curious to see if @Madddcow were to install my fork if he had the same issues.  I made other changes.

while I have no doubt trakt has problems of its own and it is part of the equation sometimes, the 30 minute interval of trakt success/fail/success/fail along with the intermittent seren fails along with the curl fails have more to do with android.

in this last log, ezra was successful at 11:49, where seren failed 12:34, and the log cut off at 11:43, six minutes before ezra was supposed to sync again.  I wonder if it failed after increasing from 30 min to 60 min.

lastly, I also hope no one here takes any comments made by me as well in any kind of way, just trying to help solve a problem.

**Comment by Madddcow** [comment] 2022-07-16 03:51
@umbrellaplug, I've removed that skin helper service and the orphaned repo...thanks for pointing those out.  I'll see how things go over the next 24 hours with Ezra and Seren.

EDIT: I've had this draft message sitting here for awhile whilst installing/configuring POV and interestingly, I haven't yet encountered any errors...and Seren is frequently the first addon to show errors.  I wonder if removing the skin helper service and orphaned repo has helped things? I can't see why that'd be the case but no errors yet is significant.

@kodifitzwell: I've installed POV and it seems to be working great.  I also like some of the little extras you've added e.g. Sync Trakt Activity (update now). Do you know if it's possible to add Orion support for your fork??

**Comment by umbrellaplug** [comment] 2022-07-16 03:57
It's probably a combination of removing all the bad repos and such combined with the skin helper service error. The skin helper service was throwing an error for an ! in it somewhere so I can't imagine it was even running anymore after that. The repos though would be taking some of your requests available from the pool of available threads. You stack enough of those up, sprinkle in some errors, and kodi being kodi and I can see a crash being likely. Hopefully that will clear you up to run ezra AND you learned about another clone. Winning.

**Comment by Madddcow** [comment] 2022-07-16 04:00
@umbrellaplug: def winning today!  Thanks for your help...much appreciated.

**Comment by kodifitzwell** [comment] 2022-07-16 04:46
@Madddcow I am unfamiliar with Orion, but looking at their website I see that ezra is compatible.  I'm unsure if it is something he added or they did.  so in theory POV should be since it is a fork of the same addon.  I'll definitely look into adding it.

**Comment by Madddcow** [comment] 2022-07-16 04:51
@kodifitzwell, Orion is a subscription indexer and search engine that often finds high-quality links.  I've contacted Orion to see if they can add support for POV.

**Comment by Ezra-Hubbard** [comment] 2022-07-16 10:46
> @kodifitzwell have you or ezra written anything into your code to handle the bad 401 responses from trakt? You were avoiding it for the most part before because the code was written in a way where it would only happen if it wasn't in an active video, but the issue is still there. Could this be part of the problem if it hasn't been fixed?

nope. nothing added

> haven't looked at all the other addons code, but I presume what is unique to Fen forks is that the error is logged to kodi.log AND a visual notification is given. so if we wanted to handle it more quietly, from trakt_api.py swap a couple lines:

yeh, that's an option, although im not sure hiding errors messages isnt just ignoring issues :')

>They stated it's happening toward the end of videos on its own, this could be related to the "upnext" changes you've been doing also. 

only next up changes were xml styling, it shouldn't impact any calls etc

>I am unfamiliar with Orion, but looking at their website I see that ezra is compatible

it is? :octocat:

**Comment by umbrellaplug** [comment] 2022-07-16 15:19
Alright. I'll be seeing myself out. Let me get out of your issues and mind my own. :)

**Comment by techrevive** [comment] 2022-07-19 19:14
Oh no you're good, I wasn't offended at all. I was laughing at myself. I think you can close this one though. I think the skin helper issue may have been his problem.

**Comment by umbrellaplug** [comment] 2022-07-19 19:26
> > 
> 
> > Alright. I'll be seeing myself out. Let me get out of your issues and mind my own. :)
> 
> Um, hope I didn't say something or come across in such a way as to cause offence? certainly wasnt intended.
> 
> really appreciate everything you do and put forward here

Nope, not at all. I replied here from the wrong account and had to delete my whole github.... :)
You see the request for new debrid service on your my account module? I'm suspicious.

**Comment by Madddcow** [comment] 2022-07-19 19:35
Hi guys. I’ve fixed up the issues pointed out to me but am still experiencing exactly the same errors with Ezra.

**Comment by Ezra-Hubbard** [comment] 2022-07-19 19:36
> > > 
> > 
> > 
> > > Alright. I'll be seeing myself out. Let me get out of your issues and mind my own. :)
> > 
> > 
> > Um, hope I didn't say something or come across in such a way as to cause offence? certainly wasnt intended.
> > really appreciate everything you do and put forward here
> 
> Nope, not at all. I replied here from the wrong account and had to delete my whole github.... :) You see the request for new debrid service on your my account module? I'm suspicious.


yeh, debrid link were spamming everyone on reddit with free subscriptions to try and get customers.

It took me 3 days and a ton of head scratching to apply global colour scheme to ezra which was only about 20 lines of python.

I wouldnt know where to start writing an entire API and scraper with no point of reference :')

**Comment by umbrellaplug** [comment] 2022-07-19 19:39
> Hi guys. I’ve fixed up the issues pointed out to me but am still experiencing exactly the same errors with Ezra.

Can you post a new log?

**Comment by Madddcow** [comment] 2022-07-21 10:54
I've disabled Ezra on my Shield for now because the onscreen Trakt sync errors were driving me (and my family) nuts; I'm now using POV instead on the Shield because there are no onscreen errors.

However, Ezra is still enabled on my bedroom Firestick and exactly the same sync errors appear onscreen...see the attached log.  As previously mentioned, these frequently appear onscreen when playback ends, regardless of which addon is used for playback i.e. Ezra, Seren, Kingpin etc.

[kodi.log](https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/files/9158663/kodi.log)

**Comment by Ezra-Hubbard** [comment] 2022-07-21 11:57
I dont know what advice or help to offer tbh. There are still a million errors in that log, all connection related. Seren having connection errors, general connection errors, loads of trakt rate exceeded errors. 

There's something fundamentally up with either your builds (you seem to have  a LOT of addons installed) or your connection :S (my hunch is still that with so many addons all polling regularly to trakt you are getting blocked for making too many requests) especially as there's no other users having this degree of trakt connection errors

The only thing I can take from this is that Ezra is the issue because it publicly notifies of an error where the rest just silently add them to the log and move on. I can look at adding option to disable error messages in settings (but it wont be a default)

**Comment by Madddcow** [comment] 2022-07-21 12:11
@Ezra-Hubbard, yeah, I know I run a bunch of video addons.  This is because I've been bitten too many times over the years when addons aren't working for some reason when I'm out and my family needs to have some other video addon options.  I think you might be right about too many addons polling regularly to Trakt and this causing blockages. I really don't think it's my connection but I could be wrong.

**Comment by umbrellaplug** [comment] 2022-07-21 12:32
One really easy way to test if this is connection or builds causing your issue would be to try vpn on your kodi and see if it makes a difference. If you jump on a vpn and the issue goes away it's  for sure a blocking/number of requests/ connection issue. If the issue is still there on a vpn it's likely the build. 

If it was the addon, trust me there would be 900 reports of it here. A nagging pop up like that will drive people crazy.

**Comment by Ezra-Hubbard** [comment] 2022-07-21 14:10
I think having multiple addons, all linked and syncing to trakt is just asking for trouble :')

Personally for your setup taking into account family etc.

Use TMDBHelper as the default for EVERYTHING on all those devices. Link that to Trakt

Install all the other addons, but DO NOT LINK THEM TO TRAKT

Have the family just use tmdb helper for everything, and then when they go to play they can just pick the player file/addon they prefer

**Comment by kodifitzwell** [comment] 2022-07-22 01:01
the "hiding errors" code above is not in my addon, so it is curious why on at least one device the same errors do not occur.  I see the firestick is arm32, is the shield arm64?

guess I won't cite any code again. lol

in any case there is the similar success/fail/success/fail pattern along with various seren and curl errors again.  the firestick is wireless?  have you moved it to another location?  have you tried the kodi speedtester addon, curious what your ping/latency/jitter are.

    0395:2022-07-21 14:47:06.963 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Success. No Changes Needed - Next Update in 60 minutes...
    0936:2022-07-21 16:37:07.921 T:1872     INFO <general>: ###Trakt Error###: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    0937:2022-07-21 16:37:07.925 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Failed. Error from Trakt - Next Update in 60 minutes...
    1111:2022-07-21 17:37:17.007 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Success - Trakt Update Performed
    1112:2022-07-21 17:37:17.008 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Widgets Refresh - Setting Disabled. Skipping Widget Refresh
    1199:2022-07-21 18:37:17.094 T:1872     INFO <general>: ###Trakt Error###: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    1200:2022-07-21 18:37:17.095 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Failed. Error from Trakt - Next Update in 60 minutes...
    1384:2022-07-21 19:37:23.387 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Success - Trakt Update Performed
    1385:2022-07-21 19:37:23.388 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Widgets Refresh - Setting Disabled. Skipping Widget Refresh
    1476:2022-07-21 20:37:23.534 T:1872     INFO <general>: ###Trakt Error###: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    1477:2022-07-21 20:37:23.535 T:1872     INFO <general>: ###EZRA###: TraktMonitor Service Update EZRA TraktMonitor - Failed. Error from Trakt - Next Update in 60 minutes...

**Comment by Madddcow** [comment] 2022-07-22 01:16
Here's the log from my Shield.  Ezra and it's support addons have been disabled and I'm running POV instead (plus all the other video addons)
[kodi.log](https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/files/9163707/kodi.log)
.

**Comment by kodifitzwell** [comment] 2022-07-22 01:36
well I did make some changes that might affect trakt, but I didn't see it on your firestick, so maybe the problem would show on POV as well.

interesting from the shield log not one error, but several seren errors.  seren logs so much it's hard to quickly wade though but some things I see are "sleep" events with no "wake" and then seren still trys to sync and fails.  what are your power saving settings on either device?

**Comment by Madddcow** [comment] 2022-07-22 02:00
My Shield was set to Sleep when my TV is turned off and that's likely to have caused the Seren sleep and wake issues.  So, I've just disabled this feature and restarted Kodi on the Shield...I'll see what the log looks like in 24 hrs.

**Closed** 2022-07-28 12:50 UTC
